# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/main.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(6, 6, 450, 300))
        self.widget.setObjectName("widget")
        self.widget1 = QtWidgets.QWidget(self.widget)
        self.widget1.setGeometry(QtCore.QRect(0, 0, 411, 91))
        self.widget1.setObjectName("widget1")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget1)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.albumArt = QtWidgets.QGraphicsView(self.widget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.albumArt.sizePolicy().hasHeightForWidth())
        self.albumArt.setSizePolicy(sizePolicy)
        self.albumArt.setMaximumSize(QtCore.QSize(90, 90))
        self.albumArt.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.albumArt.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.albumArt.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.albumArt.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.albumArt.setSceneRect(QtCore.QRectF(0.0, 0.0, 0.0, 0.0))
        self.albumArt.setObjectName("albumArt")
        self.horizontalLayout.addWidget(self.albumArt)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setContentsMargins(5, -1, -1, -1)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.artsitName = QtWidgets.QLabel(self.widget1)
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        font.setPointSize(12)
        self.artsitName.setFont(font)
        self.artsitName.setObjectName("artsitName")
        self.verticalLayout.addWidget(self.artsitName)
        self.albumName = QtWidgets.QLabel(self.widget1)
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        font.setPointSize(10)
        self.albumName.setFont(font)
        self.albumName.setObjectName("albumName")
        self.verticalLayout.addWidget(self.albumName)
        self.songName = QtWidgets.QLabel(self.widget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.songName.sizePolicy().hasHeightForWidth())
        self.songName.setSizePolicy(sizePolicy)
        self.songName.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        font.setPointSize(14)
        self.songName.setFont(font)
        self.songName.setObjectName("songName")
        self.verticalLayout.addWidget(self.songName)
        self.horizontalLayout.addLayout(self.verticalLayout)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.artsitName.setText(_translate("MainWindow", "Unknown Artist"))
        self.albumName.setText(_translate("MainWindow", "Unknown Album"))
        self.songName.setText(_translate("MainWindow", "Unknown Song"))
